mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: true

mode: rule
log-level: warning

external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.localhost"
    - "time.*"
    - "ntp.*"
    - "stun.*.*"
    - "stun.*.*.*"

  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  nameserver:
    - 223.5.5.5
    - 119.29.29.29

  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - tls://8.8.4.4

  fallback-filter:
    geoip: true
    geoip-code: CN

rule-providers:
  emos_proxy:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/binaryu/emos-proxy-rule/main/rules/emos-mihomo.yaml
    path: ./ruleset/emos-mihomo.yaml
    interval: 86400

rules:
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - RULE-SET,emos_proxy,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT

  - MATCH,PROXY