[custom]
clash_rule_base=https://raw.githubusercontent.com/binaryu/emos-proxy-rule/refs/heads/main/config/ClashConfig.yml
enable_rule_generator=true
overwrite_original_rules=true

; ---------------- 规则分流 (Ruleset) ----------------
ruleset=广告拦截,https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Surge-RULE-SET.list

ruleset=AI服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=AI服务,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list

ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list

ruleset=节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=全球直连,[]GEOIP,CN

ruleset=漏网之鱼,[]FINAL

; ---------------- 代理分组 (Groups) ----------------
custom_proxy_group=节点选择`select`[]HK节点`[]TW节点`[]SG节点`[]JP节点`[]US节点
custom_proxy_group=国外媒体`select`[]节点选择`[]HK节点`[]TW节点`[]SG节点`[]JP节点`[]US节点
custom_proxy_group=AI服务`select`[]节点选择`[]US节点`[]SG节点`[]JP节点`[]TW节点
custom_proxy_group=微软服务`select`[]DIRECT`[]节点选择`[]HK节点`[]TW节点`[]SG节点`[]JP节点`[]US节点
custom_proxy_group=广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=全球直连`select`[]DIRECT`[]节点选择
custom_proxy_group=漏网之鱼`select`[]节点选择`[]DIRECT

custom_proxy_group=HK节点`select`(港|HK|hk|Hong|Hkg|HKG)
custom_proxy_group=JP节点`select`(日|JP|jp|Japan|Jap|Tokyo|日本|东京|大阪|NRT|KIX)
custom_proxy_group=US节点`select`(美|US|us|United|States|America|lax|Sjc|Sea|LAX|SJC|SEA)
custom_proxy_group=TW节点`select`(台|TW|tw|Taiwan|Tai|TPE|KHH|新北|彰化)
custom_proxy_group=SG节点`select`(新|坡|SG|sg|Singapore|Sing|SIN|sin)